### ISSUE TITLE
ERROR: current segment is 70755198 73174848, position is 7

### ISSUE THREAD

**Issue by Steven-ZWQ** [joepickrell/gwas-pw#8]
"ERROR: current segment is 10249396 12586797, position is 1" was fixed as Dataset was ordered as suggested "tbl<-tbl[order(as.numeric(as.factor(tbl$CHR)),as.numeric(tbl$POS)),]"
However, the "ERROR: current segment is 70755198 73174848, position is 7" came.
How do you fix it?

**Comment by jcarmar** [comment]
I think you solved that but I had the same issue, and manage to solve it, and just wanted to leave it here in case someone can find the same issue. 

In my case, after changing chromosomes from "1" to "chr1" and ordering the data by chromosome and position, I still had the error. 
In my case the problem was one SNP position that changed from 7000000 to 7e+8 after saving it in R. I solve it in R doing: 

> tbl$POS <- format(tbl$POS, scientific =FALSE)

Hope this can help someone.
